name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint check
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          jupyter: true
          version: "22.3.0"
      - name: Test with pytest
        run: |
          python -m pytest tests